model_name: DenseNet2
model_hparams:
  num_classes: 10
  num_layers:
  - 6
  - 6
  - 6
  - 6
  bn_size: 2
  growth_rate: 16
  act_fn_name: relu
optimizer_name: Adam
optimizer_hparams:
  lr: 0.001
  weight_decay: 0.0001
